import { Config } from 'tailwindcss';
import defaultTheme from 'tailwindcss/defaultTheme';

const config = {
  content: ['./src/**/*.{ts,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    borderRadius: {
      none: 'var(--pw-ref-radius-none)',
      sm: 'var(--pw-ref-radius-sm)',
      base: 'var(--pw-ref-radius-base)',
      DEFAULT: 'var(--pw-ref-radius-base)',
      md: 'var(--pw-ref-radius-md)',
      lg: 'var(--pw-ref-radius-lg)',
      xl: 'var(--pw-ref-radius-xl)',
      '2xl': 'var(--pw-ref-radius-2xl)',
      '3xl': 'var(--pw-ref-radius-3xl)',
      full: 'var(--pw-ref-radius-full)',
    },
    colors: {
      white: {
        '50': 'var(--pw-ref-color-white-50)',
        '100': 'var(--pw-ref-color-white-100)',
        '200': 'var(--pw-ref-color-white-200)',
        '300': 'var(--pw-ref-color-white-300)',
        '400': 'var(--pw-ref-color-white-400)',
        '500': 'var(--pw-ref-color-white-500)',
        '600': 'var(--pw-ref-color-white-600)',
        '700': 'var(--pw-ref-color-white-700)',
        '800': 'var(--pw-ref-color-white-800)',
        '900': 'var(--pw-ref-color-white-900)',
        '950': 'var(--pw-ref-color-white-950)',
        '1000': 'var(--pw-ref-color-white-1000)',
      },
      black: {
        '50': 'var(--pw-ref-color-black-50)',
        '100': 'var(--pw-ref-color-black-100)',
        '200': 'var(--pw-ref-color-black-200)',
        '300': 'var(--pw-ref-color-black-300)',
        '400': 'var(--pw-ref-color-black-400)',
        '500': 'var(--pw-ref-color-black-500)',
        '600': 'var(--pw-ref-color-black-600)',
        '700': 'var(--pw-ref-color-black-700)',
        '800': 'var(--pw-ref-color-black-800)',
        '900': 'var(--pw-ref-color-black-900)',
        '950': 'var(--pw-ref-color-black-950)',
        '1000': 'var(--pw-ref-color-black-1000)',
      },
      blue: {
        '50': 'var(--pw-ref-color-blue-50)',
        '100': 'var(--pw-ref-color-blue-100)',
        '200': 'var(--pw-ref-color-blue-200)',
        '300': 'var(--pw-ref-color-blue-300)',
        '400': 'var(--pw-ref-color-blue-400)',
        '500': 'var(--pw-ref-color-blue-500)',
        '600': 'var(--pw-ref-color-blue-600)',
        '700': 'var(--pw-ref-color-blue-700)',
        '800': 'var(--pw-ref-color-blue-800)',
        '900': 'var(--pw-ref-color-blue-900)',
        '950': 'var(--pw-ref-color-blue-950)',
        '1000': 'var(--pw-ref-color-blue-1000)',
      },
      green: {
        '50': 'var(--pw-ref-color-green-50)',
        '100': 'var(--pw-ref-color-green-100)',
        '200': 'var(--pw-ref-color-green-200)',
        '300': 'var(--pw-ref-color-green-300)',
        '400': 'var(--pw-ref-color-green-400)',
        '500': 'var(--pw-ref-color-green-500)',
        '600': 'var(--pw-ref-color-green-600)',
        '700': 'var(--pw-ref-color-green-700)',
        '800': 'var(--pw-ref-color-green-800)',
        '900': 'var(--pw-ref-color-green-900)',
        '950': 'var(--pw-ref-color-green-950)',
        '1000': 'var(--pw-ref-color-green-1000)',
      },
      yellow: {
        '50': 'var(--pw-ref-color-yellow-50)',
        '100': 'var(--pw-ref-color-yellow-100)',
        '200': 'var(--pw-ref-color-yellow-200)',
        '300': 'var(--pw-ref-color-yellow-300)',
        '400': 'var(--pw-ref-color-yellow-400)',
        '500': 'var(--pw-ref-color-yellow-500)',
        '600': 'var(--pw-ref-color-yellow-600)',
        '700': 'var(--pw-ref-color-yellow-700)',
        '800': 'var(--pw-ref-color-yellow-800)',
        '900': 'var(--pw-ref-color-yellow-900)',
        '950': 'var(--pw-ref-color-yellow-950)',
        '1000': 'var(--pw-ref-color-yellow-1000)',
      },
      red: {
        '50': 'var(--pw-ref-color-red-50)',
        '100': 'var(--pw-ref-color-red-100)',
        '200': 'var(--pw-ref-color-red-200)',
        '300': 'var(--pw-ref-color-red-300)',
        '400': 'var(--pw-ref-color-red-400)',
        '500': 'var(--pw-ref-color-red-500)',
        '600': 'var(--pw-ref-color-red-600)',
        '700': 'var(--pw-ref-color-red-700)',
        '800': 'var(--pw-ref-color-red-800)',
        '900': 'var(--pw-ref-color-red-900)',
        '950': 'var(--pw-ref-color-red-950)',
        '1000': 'var(--pw-ref-color-red-1000)',
      },
      foreground: 'var(--pw-sys-color-foreground)',
      'foreground-on-primary': 'var(--pw-sys-color-foreground-on-primary)',
      'foreground-secondary': 'var(--pw-sys-color-foreground-secondary)',
      'foreground-on-secondary': 'var(--pw-sys-color-foreground-on-secondary)',
      'foreground-info': 'var(--pw-sys-color-foreground-info)',
      'foreground-on-info': 'var(--pw-sys-color-foreground-on-info)',
      'foreground-on-info-subdued':
        'var(--pw-sys-color-foreground-on-info-subdued)',
      'foreground-success': 'var(--pw-sys-color-foreground-success)',
      'foreground-on-success': 'var(--pw-sys-color-foreground-on-success)',
      'foreground-on-success-subdued':
        'var(--pw-sys-color-foreground-on-success-subdued)',
      'foreground-caution': 'var(--pw-sys-color-foreground-caution)',
      'foreground-on-caution': 'var(--pw-sys-color-foreground-on-caution)',
      'foreground-on-caution-subdued':
        'var(--pw-sys-color-foreground-on-caution-subdued)',
      'foreground-critical': 'var(--pw-sys-color-foreground-critical)',
      'foreground-on-critical': 'var(--pw-sys-color-foreground-on-critical)',
      'foreground-on-critical-subdued':
        'var(--pw-sys-color-foreground-on-critical-subdued)',
      'foreground-disabled': 'var(--pw-sys-color-foreground-disabled)',
      'foreground-on-disabled': 'var(--pw-sys-color-foreground-on-disabled)',
      background: 'var(--pw-sys-color-background)',
      'background-primary': 'var(--pw-sys-color-background-primary)',
      'background-primary-hover':
        'var(--pw-sys-color-background-primary-hover)',
      'background-secondary': 'var(--pw-sys-color-background-secondary)',
      'background-secondary-hover':
        'var(--pw-sys-color-background-secondary-hover)',
      'background-info': 'var(--pw-sys-color-background-info)',
      'background-info-hover': 'var(--pw-sys-color-background-info-hover)',
      'background-info-subdued': 'var(--pw-sys-color-background-info-subdued)',
      'background-info-subdued-hover':
        'var(--pw-sys-color-background-info-subdued-hover)',
      'background-success': 'var(--pw-sys-color-background-success)',
      'background-success-hover':
        'var(--pw-sys-color-background-success-hover)',
      'background-success-subdued':
        'var(--pw-sys-color-background-success-subdued)',
      'background-success-subdued-hover':
        'var(--pw-sys-color-background-success-subdued-hover)',
      'background-caution': 'var(--pw-sys-color-background-caution)',
      'background-caution-hover':
        'var(--pw-sys-color-background-caution-hover)',
      'background-caution-subdued':
        'var(--pw-sys-color-background-caution-subdued)',
      'background-caution-subdued-hover':
        'var(--pw-sys-color-background-caution-subdued-hover)',
      'background-critical': 'var(--pw-sys-color-background-critical)',
      'background-critical-hover':
        'var(--pw-sys-color-background-critical-hover)',
      'background-critical-subdued':
        'var(--pw-sys-color-background-critical-subdued)',
      'background-critical-subdued-hover':
        'var(--pw-sys-color-background-critical-subdued-hover)',
      'background-disabled': 'var(--pw-sys-color-background-disabled)',
      border: 'var(--pw-sys-color-border)',
      'border-secondary': 'var(--pw-sys-color-border-secondary)',
      'border-info': 'var(--pw-sys-color-border-info)',
      'border-success': 'var(--pw-sys-color-border-success)',
      'border-caution': 'var(--pw-sys-color-border-caution)',
      'border-critical': 'var(--pw-sys-color-border-critical)',
      'border-disabled': 'var(--pw-sys-color-border-disabled)',
      ring: 'var(--pw-sys-color-ring)',
      'ring-secondary': 'var(--pw-sys-color-ring-secondary)',
      'ring-info': 'var(--pw-sys-color-ring-info)',
      'ring-success': 'var(--pw-sys-color-ring-success)',
      'ring-caution': 'var(--pw-sys-color-ring-caution)',
      'ring-critical': 'var(--pw-sys-color-ring-critical)',
      'ring-disabled': 'var(--pw-sys-color-ring-disabled)',
      outline: 'var(--pw-sys-color-outline)',
      'outline-secondary': 'var(--pw-sys-color-outline-secondary)',
      'outline-info': 'var(--pw-sys-color-outline-info)',
      'outline-success': 'var(--pw-sys-color-outline-success)',
      'outline-caution': 'var(--pw-sys-color-outline-caution)',
      'outline-critical': 'var(--pw-sys-color-outline-critical)',
      'outline-disabled': 'var(--pw-sys-color-outline-disabled)',
    },
    extend: {
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
      },
    },
  },
  plugins: [],
} satisfies Config;

export default config;
