import { cva } from 'class-variance-authority';

export const switchContainerVariants = cva(
  [
    'group',
    'relative',
    'rounded-full',
    'inline-flex items-center',
    'w-13 min-w-13 h-8',
    'border-outline border-2',
    'bg-surface-container-highest',
    'easing-emphasized duration-medium-1 transition',
    'data-[disabled=false]:cursor-pointer',
    'data-[disabled]:data-[selected=true]:border-transparent',
    'data-[disabled=true]:border-on-surface/[0.12]',
    'data-[disabled=true]:bg-surface-container-highest/[0.12]',
    'data-[disabled=true]:data-[selected=true]:bg-on-surface/[0.12]',
  ],
  {
    variants: {
      color: {
        primary: ['data-[selected=true]:bg-primary'],
        secondary: ['data-[selected=true]:bg-secondary'],
        info: ['data-[selected=true]:bg-info'],
        success: ['data-[selected=true]:bg-success'],
        caution: ['data-[selected=true]:bg-caution'],
        critical: ['data-[selected=true]:bg-critical'],
      },
    },
    defaultVariants: {
      color: 'primary',
    },
  },
);

export const switchThumbVariants = cva(
  [
    'absolute',
    'rounded-full',
    'inline-flex items-center justify-center',
    'size-7',
    '[&>svg]:absolute',
    '[&>svg]:z-1',
    '[&>svg]:starting:size-0 [&>svg]:size-4',
    '[&>svg]:transition-not-color [&>svg]:easing-emphasized [&>svg]:duration-medium-1',
    'group-data-[selected=true]:translate-x-5',
    'easing-emphasized duration-medium-1 transition',
    'text-surface-container-highest',
    'group-data-[disabled=true]:text-surface-container-highest/[0.38]',
    'group-data-[disabled=true]:group-data-[selected=true]:text-on-surface/[0.38]',
    'string:rounded-full',
    'ring:size-4',
    'ring:absolute',
    'ring:transition ring:easing-emphasized ring:duration-medium-1',
    'group-data-[selected=true]:ring:scale-150',
    'group-data-[icon=true]:ring:scale-150',
    'group-data-[selected]:group-data-[pressed=true]:ring:scale-[1.75]',
    'ring:bg-outline',
    'group-hover:ring:bg-on-surface-variant',
    'group-focus-within:ring:bg-on-surface-variant',
    'group-data-[disabled=true]:ring:bg-on-surface/[0.38]',
    'group-data-[disabled=true]:group-data-[selected=true]:ring:bg-surface',
    'state:size-10',
    'state:absolute state:left-1/2 state:top-1/2 state:-translate-x-1/2 state:-translate-y-1/2',
    'state:transition state:easing-emphasized state:duration-medium-1',
    'group-hover:state:bg-on-surface/[0.08]',
    'group-focus-within:state:bg-on-surface/[0.12]',
    'group-data-[pressed=true]:state:bg-on-surface/[0.12]',
    'group-data-[disabled=true]:group-data-[selected]:state:hidden',
  ],
  {
    variants: {
      color: {
        primary: [
          'group-data-[selected=true]:text-primary',
          'group-hover:group-data-[selected=true]:text-on-primary-container',
          'group-focus-within:group-data-[selected=true]:text-on-primary-container',
          'group-data-[selected=true]:ring:bg-on-primary',
          'group-hover:group-data-[disabled=false]:group-data-[selected=true]:ring:bg-primary-container',
          'group-focus-within:group-data-[selected=true]:ring:bg-primary-container',
          'group-hover:group-data-[selected=true]:state:bg-primary/[0.08]',
          'group-focus-within:group-data-[selected=true]:state:bg-primary/[0.12]',
          'group-data-[pressed=true]:group-data-[selected=true]:state:bg-primary/[0.12]',
        ],
        secondary: [
          'group-data-[selected=true]:text-secondary',
          'group-hover:group-data-[selected=true]:text-on-secondary-container',
          'group-focus-within:group-data-[selected=true]:text-on-secondary-container',
          'group-data-[selected=true]:ring:bg-on-secondary',
          'group-hover:group-data-[disabled=false]:group-data-[selected=true]:ring:bg-secondary-container',
          'group-focus-within:group-data-[selected=true]:ring:bg-secondary-container',
          'group-hover:group-data-[selected=true]:state:bg-secondary/[0.08]',
          'group-focus-within:group-data-[selected=true]:state:bg-secondary/[0.12]',
          'group-data-[pressed=true]:group-data-[selected=true]:state:bg-secondary/[0.12]',
        ],
        info: [
          'group-data-[selected=true]:text-info',
          'group-hover:group-data-[selected=true]:text-on-info-container',
          'group-focus-within:group-data-[selected=true]:text-on-info-container',
          'group-data-[selected=true]:ring:bg-on-info',
          'group-hover:group-data-[disabled=false]:group-data-[selected=true]:ring:bg-info-container',
          'group-focus-within:group-data-[selected=true]:ring:bg-info-container',
          'group-hover:group-data-[selected=true]:state:bg-info/[0.08]',
          'group-focus-within:group-data-[selected=true]:state:bg-info/[0.12]',
          'group-data-[pressed=true]:group-data-[selected=true]:state:bg-info/[0.12]',
        ],
        success: [
          'group-data-[selected=true]:text-success',
          'group-hover:group-data-[selected=true]:text-on-success-container',
          'group-focus-within:group-data-[selected=true]:text-on-success-container',
          'group-data-[selected=true]:ring:bg-on-success',
          'group-hover:group-data-[disabled=false]:group-data-[selected=true]:ring:bg-success-container',
          'group-focus-within:group-data-[selected=true]:ring:bg-success-container',
          'group-hover:group-data-[selected=true]:state:bg-success/[0.08]',
          'group-focus-within:group-data-[selected=true]:state:bg-success/[0.12]',
          'group-data-[pressed=true]:group-data-[selected=true]:state:bg-success/[0.12]',
        ],
        caution: [
          'group-data-[selected=true]:text-caution',
          'group-hover:group-data-[selected=true]:text-on-caution-container',
          'group-focus-within:group-data-[selected=true]:text-on-caution-container',
          'group-data-[selected=true]:ring:bg-on-caution',
          'group-hover:group-data-[disabled=false]:group-data-[selected=true]:ring:bg-caution-container',
          'group-focus-within:group-data-[selected=true]:ring:bg-caution-container',
          'group-hover:group-data-[selected=true]:state:bg-caution/[0.08]',
          'group-focus-within:group-data-[selected=true]:state:bg-caution/[0.12]',
          'group-data-[pressed=true]:group-data-[selected=true]:state:bg-caution/[0.12]',
        ],
        critical: [
          'group-data-[selected=true]:text-critical',
          'group-hover:group-data-[selected=true]:text-on-critical-container',
          'group-focus-within:group-data-[selected=true]:text-on-critical-container',
          'group-data-[selected=true]:ring:bg-on-critical',
          'group-hover:group-data-[disabled=false]:group-data-[selected=true]:ring:bg-critical-container',
          'group-focus-within:group-data-[selected=true]:ring:bg-critical-container',
          'group-hover:group-data-[selected=true]:state:bg-critical/[0.08]',
          'group-focus-within:group-data-[selected=true]:state:bg-critical/[0.12]',
          'group-data-[pressed=true]:group-data-[selected=true]:state:bg-critical/[0.12]',
        ],
      },
    },
    defaultVariants: {
      color: 'primary',
    },
  },
);
