import { cva } from 'class-variance-authority';

export const checkboxWrapperVariants = cva([
  'group/checkbox',
  'inline-flex items-center gap-xs',
  'typography-body-large',
  'select-none',
]);

export const checkboxTargetVariants = cva([
  'group/checkbox--target relative inline-flex size-10 items-center justify-center',
  'hovered:cursor-pointer',
  'state:-z-1 state:size-10 state:rounded-full',
  'state:absolute',
  'state:left-1/2 state:top-1/2',
  'state:-translate-x-1/2 state:-translate-y-1/2',
  'state:transition-[background-color_medium-1_emphasized]',
  'group-data-[disabled=true]/checkbox:state:hidden',
  'hovered:state:bg-on-surface/[0.08]',
  'focus-visible-within:state:bg-on-surface/[0.12]',
  'pressed:state:bg-on-surface/[0.12]',
  'ripple:bg-on-surface/[0.12]',
  'hovered:group-data-[invalid=true]/checkbox:state:bg-critical/[0.08]',
  'focus-visible-within:group-data-[invalid=true]/checkbox:state:bg-critical/[0.12]',
  'pressed:group-data-[invalid=true]/checkbox:state:bg-critical/[0.12]',
  'group-data-[invalid=true]/checkbox:ripple:bg-critical/[0.12]',
  'ripple-wrapper:rounded-full',
  'ripple-wrapper:inset-0',
]);

export const checkboxContainerVariants = cva(
  [
    'relative',
    'size-4.5 min-w-4.5',
    'rounded-3xs',
    'border-2',
    'inline-flex items-center justify-center',
    'transition-[box-shadow,color,background-color,border-color_medium-1_emphasized-decelerate]',
    'group-data-[disabled=false]/checkbox:cursor-pointer',
    '[&>svg]:z-1',
    '[&>svg]:absolute',
    '[&>svg]:size-4.5',
    '[&>svg]:transition-[scale_medium-1_emphasized-decelerate]',
    '[&>svg]:scale-100',
    '[&>svg]:starting:scale-0',
    'text-on-surface',
    'border-on-surface-variant',
    'group-data-[selected=true]/checkbox:border-transparent',
    'group-data-[disabled=false]/checkbox:group-data-[selected=true]/checkbox:group-data-[invalid=true]/checkbox:text-on-critical',
    'group-data-[disabled=false]/checkbox:group-data-[selected]/checkbox:group-data-[invalid=true]/checkbox:border-critical',
    'group-data-[disabled=false]/checkbox:group-data-[selected=true]/checkbox:group-data-[invalid=true]/checkbox:bg-critical',
    'group-data-[disabled=true]/checkbox:group-data-[selected=false]/checkbox:border-on-surface/[0.38]',
    'group-data-[disabled=true]/checkbox:group-data-[selected=true]/checkbox:bg-on-surface/[0.38]',
    'group-data-[disabled=true]/checkbox:text-surface',
  ],
  {
    variants: {
      color: {
        primary: [
          'group-data-[selected=true]/checkbox:bg-primary',
          'group-data-[selected=true]/checkbox:text-on-primary',
          'group-data-[selected=true]/checkbox:group-hovered/checkbox--target:group-state/checkbox--target:bg-primary/[0.08]',
          'group-data-[selected=true]/checkbox:group-focus-visible-within/checkbox--target:group-state/checkbox--target:bg-primary/[0.12]',
          'group-data-[selected=true]/checkbox:group-pressed/checkbox--target:group-state/checkbox--target:bg-primary/[0.12]',
          'group-data-[selected=true]/checkbox:group-ripple/checkbox--target:bg-primary/[0.12]',
        ],
        secondary: [
          'group-data-[selected=true]/checkbox:bg-secondary',
          'group-data-[selected=true]/checkbox:text-on-secondary',
          'group-data-[selected=true]/checkbox:group-hovered/checkbox--target:group-state/checkbox--target:bg-secondary/[0.08]',
          'group-data-[selected=true]/checkbox:group-focus-visible-within/checkbox--target:group-state/checkbox--target:bg-secondary/[0.12]',
          'group-data-[selected=true]/checkbox:group-pressed/checkbox--target:group-state/checkbox--target:bg-secondary/[0.12]',
          'group-data-[selected=true]/checkbox:group-ripple/checkbox--target:bg-secondary/[0.12]',
        ],
        info: [
          'group-data-[selected=true]/checkbox:bg-info',
          'group-data-[selected=true]/checkbox:text-on-info',
          'group-data-[selected=true]/checkbox:group-hovered/checkbox--target:group-state/checkbox--target:bg-info/[0.08]',
          'group-data-[selected=true]/checkbox:group-focus-visible-within/checkbox--target:group-state/checkbox--target:bg-info/[0.12]',
          'group-data-[selected=true]/checkbox:group-pressed/checkbox--target:group-state/checkbox--target:bg-info/[0.12]',
          'group-data-[selected=true]/checkbox:group-ripple/checkbox--target:bg-info/[0.12]',
        ],
        success: [
          'group-data-[selected=true]/checkbox:bg-success',
          'group-data-[selected=true]/checkbox:text-on-success',
          'group-data-[selected=true]/checkbox:group-hovered/checkbox--target:group-state/checkbox--target:bg-success/[0.08]',
          'group-data-[selected=true]/checkbox:group-focus-visible-within/checkbox--target:group-state/checkbox--target:bg-success/[0.12]',
          'group-data-[selected=true]/checkbox:group-pressed/checkbox--target:group-state/checkbox--target:bg-success/[0.12]',
          'group-data-[selected=true]/checkbox:group-ripple/checkbox--target:bg-success/[0.12]',
        ],
        caution: [
          'group-data-[selected=true]/checkbox:bg-caution',
          'group-data-[selected=true]/checkbox:text-on-caution',
          'group-data-[selected=true]/checkbox:group-hovered/checkbox--target:group-state/checkbox--target:bg-caution/[0.08]',
          'group-data-[selected=true]/checkbox:group-focus-visible-within/checkbox--target:group-state/checkbox--target:bg-caution/[0.12]',
          'group-data-[selected=true]/checkbox:group-pressed/checkbox--target:group-state/checkbox--target:bg-caution/[0.12]',
          'group-data-[selected=true]/checkbox:group-ripple/checkbox--target:bg-caution/[0.12]',
        ],
        critical: [
          'group-data-[selected=true]/checkbox:bg-critical',
          'group-data-[selected=true]/checkbox:text-on-critical',
          'group-data-[selected=true]/checkbox:group-hovered/checkbox--target:group-state/checkbox--target:bg-critical/[0.08]',
          'group-data-[selected=true]/checkbox:group-focus-visible-within/checkbox--target:group-state/checkbox--target:bg-critical/[0.12]',
          'group-data-[selected=true]/checkbox:group-pressed/checkbox--target:group-state/checkbox--target:bg-critical/[0.12]',
          'group-data-[selected=true]/checkbox:group-ripple/checkbox--target:bg-critical/[0.12]',
        ],
      },
    },
    defaultVariants: {
      color: 'primary',
    },
  },
);
