import { cva } from 'class-variance-authority';

export const iconButtonVariants = cva(
  [
    'group/icon-button relative',
    'inline-flex items-center justify-center',
    'size-10 min-w-10 rounded-lg',
    '[&>svg]:size-6 [&>svg]:starting:size-0',
    '[&>svg]:transition-[color,width,height_medium-1_emphasized-decelerate]',
    'transition-[box-shadow,color,background-color,border-color_medium-1_emphasized-decelerate]',
    'select-none outline-none',
    'disabled:pointer-events-none',
    'whitespace-nowrap',
    'border border-transparent',
    '[&>*]:z-1',
    'string:absolute string:rounded-lg',
    'state:transition-[background-color_medium-1_emphasized]',
    'state:-inset-0.5',
    'ring:-inset-1',
    'ring:transition-[box-shadow_medium-1_emphasized-accelerate]',
    'ring:hidden focus-visible:ring:block',
    'ring:ring-4 starting:ring:ring-8',
    'ring:ring-primary-container',
    'ripple-wrapper:rounded-lg',
    'ripple-wrapper:-inset-0.5',
  ],
  {
    variants: {
      variant: {
        standard: [
          'text-on-surface-variant',
          'hovered:state:bg-on-surface-variant/[0.08]',
          'focus-visible:state:bg-on-surface-variant/[0.12]',
          'pressed:state:bg-on-surface-variant/[0.12]',
          'ripple:bg-on-surface-variant/[0.12]',
          'data-[selected]:data-[disabled=true]:text-on-surface/[0.38]',
        ],
        filled: [
          'data-[disabled=true]:bg-on-surface/[0.12]',
          'data-[disabled=true]:text-on-surface/[0.38]',
          'data-[toggleable]:data-[selected]:data-[disabled=true]:bg-on-surface/[0.12]',
          'data-[toggleable]:data-[selected]:data-[disabled=true]:text-on-surface/[0.38]',
        ],
        tonal: [
          'data-[toggleable]:data-[selected=false]:bg-surface-container-highest',
          'data-[toggleable]:data-[selected=false]:text-on-surface-variant',
          'hovered:data-[toggleable]:data-[selected=false]:state:bg-on-surface-variant/[0.08]',
          'focus-visible:data-[toggleable]:data-[selected=false]:state:bg-on-surface-variant/[0.12]',
          'pressed:data-[toggleable]:data-[selected=false]:state:bg-on-surface-variant/[0.12]',
          'ripple:data-[toggleable]:data-[selected=false]:bg-on-surface-variant/[0.12]',
          'data-[disabled=true]:bg-on-surface/[0.12]',
          'data-[disabled=true]:text-on-surface/[0.38]',
          'data-[toggleable]:data-[selected]:data-[disabled=true]:bg-on-surface/[0.12]',
          'data-[toggleable]:data-[selected]:data-[disabled=true]:text-on-surface/[0.38]',
        ],
        outlined: [
          'text-on-surface-variant',
          'border-outline',
          'hovered:state:bg-on-surface-variant/[0.08]',
          'focus-visible:state:bg-on-surface-variant/[0.08]',
          'pressed:state:bg-on-surface-variant/[0.12]',
          'ripple:bg-on-surface-variant/[0.12]',
          'data-[toggleable]:data-[selected=true]:text-surface',
          'data-[toggleable]:data-[selected=true]:border-transparent',
          'data-[toggleable]:data-[selected=true]:bg-on-surface',
          'hovered:data-[toggleable]:data-[selected=true]:state:bg-surface/[0.08]',
          'focus-visible:data-[toggleable]:data-[selected=true]:state:bg-surface/[0.12]',
          'pressed:data-[toggleable]:data-[selected=true]:state:bg-surface/[0.12]',
          'ripple:data-[toggleable]:data-[selected=true]:bg-surface/[0.12]',
          'data-[disabled=true]:text-on-surface/[0.38]',
          'data-[disabled=true]:border-on-surface/[0.12]',
          'data-[toggleable]:data-[selected=false]:data-[disabled=true]:text-on-surface/[0.38]',
          'data-[toggleable]:data-[selected=false]:data-[disabled=true]:border-on-surface/[0.12]',
          'data-[toggleable]:data-[selected=true]:data-[disabled=true]:text-on-surface/[0.38]',
          'data-[toggleable]:data-[selected=true]:data-[disabled=true]:bg-on-surface/[0.12]',
        ],
      },
      color: {
        primary: [],
        secondary: [],
        info: [],
        success: [],
        caution: [],
        critical: [],
      },
    },
    defaultVariants: {
      color: 'primary',
      variant: 'standard',
    },
    compoundVariants: [
      // #region Standard
      {
        variant: 'standard',
        color: 'primary',
        className: [
          'data-[selected=true]:text-primary-foreground',
          'hovered:data-[selected=true]:state:bg-primary/[0.08]',
          'focus-visible:data-[selected=true]:state:bg-primary/[0.12]',
          'pressed:data-[selected=true]:state:bg-primary/[0.12]',
          'ripple:data-[selected=true]:bg-primary/[0.12]',
        ],
      },
      {
        variant: 'standard',
        color: 'secondary',
        className: [
          'data-[selected=true]:text-secondary-foreground',
          'hovered:data-[selected=true]:state:bg-secondary/[0.08]',
          'focus-visible:data-[selected=true]:state:bg-secondary/[0.12]',
          'pressed:data-[selected=true]:state:bg-secondary/[0.12]',
          'ripple:data-[selected=true]:bg-secondary/[0.12]',
        ],
      },
      {
        variant: 'standard',
        color: 'info',
        className: [
          'data-[selected=true]:text-info-foreground',
          'hovered:data-[selected=true]:state:bg-info/[0.08]',
          'focus-visible:data-[selected=true]:state:bg-info/[0.12]',
          'pressed:data-[selected=true]:state:bg-info/[0.12]',
          'ripple:data-[selected=true]:bg-info/[0.12]',
        ],
      },
      {
        variant: 'standard',
        color: 'success',
        className: [
          'data-[selected=true]:text-success-foreground',
          'hovered:data-[selected=true]:state:bg-success/[0.08]',
          'focus-visible:data-[selected=true]:state:bg-success/[0.12]',
          'pressed:data-[selected=true]:state:bg-success/[0.12]',
          'ripple:data-[selected=true]:bg-success/[0.12]',
        ],
      },
      {
        variant: 'standard',
        color: 'caution',
        className: [
          'data-[selected=true]:text-caution-foreground',
          'hovered:data-[selected=true]:state:bg-caution/[0.08]',
          'focus-visible:data-[selected=true]:state:bg-caution/[0.12]',
          'pressed:data-[selected=true]:state:bg-caution/[0.12]',
          'ripple:data-[selected=true]:bg-caution/[0.12]',
        ],
      },
      {
        variant: 'standard',
        color: 'critical',
        className: [
          'data-[selected=true]:text-critical-foreground',
          'hovered:data-[selected=true]:state:bg-critical/[0.08]',
          'focus-visible:data-[selected=true]:state:bg-critical/[0.12]',
          'pressed:data-[selected=true]:state:bg-critical/[0.12]',
          'ripple:data-[selected=true]:bg-critical/[0.12]',
        ],
      },
      // #endregion Standard

      // #region Filled
      {
        variant: 'filled',
        color: 'primary',
        className: [
          'bg-primary',
          'text-on-primary',
          'hovered:state:bg-on-primary/[0.08]',
          'focus-visible:state:bg-on-primary/[0.12]',
          'pressed:state:bg-on-primary/[0.12]',
          'ripple:bg-on-primary/[0.12]',
          'data-[toggleable]:data-[selected=false]:bg-surface-container-highest',
          'data-[toggleable]:data-[selected=false]:text-primary-foreground',
          'hovered:data-[toggleable]:data-[selected=false]:state:bg-primary/[0.08]',
          'focus-visible:data-[toggleable]:data-[selected=false]:state:bg-primary/[0.12]',
          'pressed:data-[toggleable]:data-[selected=false]:state:bg-primary/[0.12]',
          'ripple:data-[toggleable]:data-[selected=false]:bg-primary/[0.12]',
        ],
      },
      {
        variant: 'filled',
        color: 'secondary',
        className: [
          'bg-secondary',
          'text-on-secondary',
          'hovered:state:bg-on-secondary/[0.08]',
          'focus-visible:state:bg-on-secondary/[0.12]',
          'pressed:state:bg-on-secondary/[0.12]',
          'ripple:bg-on-secondary/[0.12]',
          'data-[toggleable]:data-[selected=false]:bg-surface-container-highest',
          'data-[toggleable]:data-[selected=false]:text-secondary-foreground',
          'hovered:data-[toggleable]:data-[selected=false]:state:bg-secondary/[0.08]',
          'focus-visible:data-[toggleable]:data-[selected=false]:state:bg-secondary/[0.12]',
          'pressed:data-[toggleable]:data-[selected=false]:state:bg-secondary/[0.12]',
          'ripple:data-[toggleable]:data-[selected=false]:bg-secondary/[0.12]',
        ],
      },
      {
        variant: 'filled',
        color: 'info',
        className: [
          'bg-info',
          'text-on-info',
          'hovered:state:bg-on-info/[0.08]',
          'focus-visible:state:bg-on-info/[0.12]',
          'pressed:state:bg-on-info/[0.12]',
          'ripple:bg-on-info/[0.12]',
          'data-[toggleable]:data-[selected=false]:bg-surface-container-highest',
          'data-[toggleable]:data-[selected=false]:text-info-foreground',
          'hovered:data-[toggleable]:data-[selected=false]:state:bg-info/[0.08]',
          'focus-visible:data-[toggleable]:data-[selected=false]:state:bg-info/[0.12]',
          'pressed:data-[toggleable]:data-[selected=false]:state:bg-info/[0.12]',
          'ripple:data-[toggleable]:data-[selected=false]:bg-info/[0.12]',
        ],
      },
      {
        variant: 'filled',
        color: 'success',
        className: [
          'bg-success',
          'text-on-success',
          'hovered:state:bg-on-success/[0.08]',
          'focus-visible:state:bg-on-success/[0.12]',
          'pressed:state:bg-on-success/[0.12]',
          'ripple:bg-on-success/[0.12]',
          'data-[toggleable]:data-[selected=false]:bg-surface-container-highest',
          'data-[toggleable]:data-[selected=false]:text-success-foreground',
          'hovered:data-[toggleable]:data-[selected=false]:state:bg-success/[0.08]',
          'focus-visible:data-[toggleable]:data-[selected=false]:state:bg-success/[0.12]',
          'pressed:data-[toggleable]:data-[selected=false]:state:bg-success/[0.12]',
          'ripple:data-[toggleable]:data-[selected=false]:bg-success/[0.12]',
        ],
      },
      {
        variant: 'filled',
        color: 'caution',
        className: [
          'bg-caution',
          'text-on-caution',
          'hovered:state:bg-on-caution/[0.08]',
          'focus-visible:state:bg-on-caution/[0.12]',
          'pressed:state:bg-on-caution/[0.12]',
          'ripple:bg-on-caution/[0.12]',
          'data-[toggleable]:data-[selected=false]:bg-surface-container-highest',
          'data-[toggleable]:data-[selected=false]:text-caution-foreground',
          'hovered:data-[toggleable]:data-[selected=false]:state:bg-caution/[0.08]',
          'focus-visible:data-[toggleable]:data-[selected=false]:state:bg-caution/[0.12]',
          'pressed:data-[toggleable]:data-[selected=false]:state:bg-caution/[0.12]',
          'ripple:data-[toggleable]:data-[selected=false]:bg-caution/[0.12]',
        ],
      },
      {
        variant: 'filled',
        color: 'critical',
        className: [
          'bg-critical',
          'text-on-critical',
          'hovered:state:bg-on-critical/[0.08]',
          'focus-visible:state:bg-on-critical/[0.12]',
          'pressed:state:bg-on-critical/[0.12]',
          'ripple:bg-on-critical/[0.12]',
          'data-[toggleable]:data-[selected=false]:bg-surface-container-highest',
          'data-[toggleable]:data-[selected=false]:text-critical-foreground',
          'hovered:data-[toggleable]:data-[selected=false]:state:bg-critical/[0.08]',
          'focus-visible:data-[toggleable]:data-[selected=false]:state:bg-critical/[0.12]',
          'pressed:data-[toggleable]:data-[selected=false]:state:bg-critical/[0.12]',
          'ripple:data-[toggleable]:data-[selected=false]:bg-critical/[0.12]',
        ],
      },
      // #endregion Filled

      // #region Tonal
      {
        variant: 'tonal',
        color: 'primary',
        className: [
          'bg-primary-container text-on-primary-container',
          'hovered:state:bg-on-primary-container/[0.08]',
          'focus-visible:state:bg-on-primary-container/[0.12]',
          'pressed:state:bg-on-primary-container/[0.12]',
          'ripple:bg-on-primary-container/[0.12]',
        ],
      },
      {
        variant: 'tonal',
        color: 'secondary',
        className: [
          'bg-secondary-container text-on-secondary-container',
          'hovered:state:bg-on-secondary-container/[0.08]',
          'focus-visible:state:bg-on-secondary-container/[0.12]',
          'pressed:state:bg-on-secondary-container/[0.12]',
          'ripple:bg-on-secondary-container/[0.12]',
        ],
      },
      {
        variant: 'tonal',
        color: 'info',
        className: [
          'bg-info-container text-on-info-container',
          'hovered:state:bg-on-info-container/[0.08]',
          'focus-visible:state:bg-on-info-container/[0.12]',
          'pressed:state:bg-on-info-container/[0.12]',
          'ripple:bg-on-info-container/[0.12]',
        ],
      },
      {
        variant: 'tonal',
        color: 'success',
        className: [
          'bg-success-container text-on-success-container',
          'hovered:state:bg-on-success-container/[0.08]',
          'focus-visible:state:bg-on-success-container/[0.12]',
          'pressed:state:bg-on-success-container/[0.12]',
          'ripple:bg-on-success-container/[0.12]',
        ],
      },
      {
        variant: 'tonal',
        color: 'caution',
        className: [
          'bg-caution-container text-on-caution-container',
          'hovered:state:bg-on-caution-container/[0.08]',
          'focus-visible:state:bg-on-caution-container/[0.12]',
          'pressed:state:bg-on-caution-container/[0.12]',
          'ripple:bg-on-caution-container/[0.12]',
        ],
      },
      {
        variant: 'tonal',
        color: 'critical',
        className: [
          'bg-critical-container text-on-critical-container',
          'hovered:state:bg-on-critical-container/[0.08]',
          'focus-visible:state:bg-on-critical-container/[0.12]',
          'pressed:state:bg-on-critical-container/[0.12]',
          'ripple:bg-on-critical-container/[0.12]',
        ],
      },
      // #endregion Tonal
    ],
  },
);
