import { cva } from 'class-variance-authority';

export const switchContainerVariants = cva(
  [
    'group',
    'relative',
    'rounded-full before:rounded-full after:rounded-full',
    'inline-flex items-center',
    'h-8 w-13 min-w-13',
    'bg-surface-container-highest',
    'border-2 border-outline',
    'transition duration-medium-2 easing-emphasized',
    'data-[disabled=false]:cursor-pointer',
    'focus-within:before:bg-surface-container-highest/[0.12]',
    'hover:before:bg-on-surface-container-highest/[0.08]',
    'data-[pressed=true]:before:bg-on-surface-container-highest/[0.12]',
    'before:absolute before:-inset-0.5',
    'before:transition before:easing-emphasized before:duration-medium-1',
    'data-[selected=true]:border-transparent',
    'data-[disabled=true]:data-[selected=true]:bg-on-surface/[0.12]',
    'data-[disabled=true]:data-[selected=false]:bg-surface-container-highest/[0.12]',
    'data-[disabled=true]:data-[selected=false]:border-on-surface/[0.12]',
  ],
  {
    variants: {
      color: {
        primary: ['data-[selected=true]:bg-primary'],
        secondary: [
          'data-[selected=true]:bg-secondary',
          'data-[selected=true]:focus-within:before:bg-secondary/[0.12]',
          'data-[selected=true]:hover:before:bg-secondary/[0.08]',
          'data-[selected=true]:data-[pressed=true]:before:bg-secondary/[0.12]',
        ],
        info: [
          'data-[selected=true]:bg-info',
          'data-[selected=true]:focus-within:before:bg-info/[0.12]',
          'data-[selected=true]:hover:before:bg-info/[0.08]',
          'data-[selected=true]:data-[pressed=true]:before:bg-info/[0.12]',
        ],
        success: [
          'data-[selected=true]:bg-success',
          'data-[selected=true]:focus-within:before:bg-success/[0.12]',
          'data-[selected=true]:hover:before:bg-success/[0.08]',
          'data-[selected=true]:data-[pressed=true]:before:bg-success/[0.12]',
        ],
        caution: [
          'data-[selected=true]:bg-caution',
          'data-[selected=true]:focus-within:before:bg-caution/[0.12]',
          'data-[selected=true]:hover:before:bg-caution/[0.08]',
          'data-[selected=true]:data-[pressed=true]:before:bg-caution/[0.12]',
        ],
        critical: [
          'data-[selected=true]:bg-critical',
          'data-[selected=true]:focus-within:before:bg-critical/[0.12]',
          'data-[selected=true]:hover:before:bg-critical/[0.08]',
          'data-[selected=true]:data-[pressed=true]:before:bg-critical/[0.12]',
        ],
      },
    },
    defaultVariants: {
      color: 'primary',
    },
  },
);

export const switchThumbVariants = cva(
  [
    'absolute',
    'transition-transform easing-emphasized duration-medium-1',
    'inline-flex items-center justify-center',
    'h-7 w-7',
    '[&>svg]:absolute',
    '[&>svg]:h-4 [&>svg]:w-4 [&>svg]:min-w-4',
    'before:h-4 before:w-4',
    'group-data-[selected=true]:translate-x-5',
    'text-surface-container-highest',
    'before:transition before:easing-emphasized before:duration-medium-1',
    'before:rounded-full',
    'before:bg-outline',
    'group-focus-within:before:bg-on-surface-variant',
    'group-hover:before:bg-on-surface-variant',
    'group-data-[pressed=true]:before:scale-[1.75]',
    'group-data-[selected=true]:before:scale-150',
    'group-data-[icon=true]:before:scale-150',
    'group-data-[disabled=true]:group-data-[selected=true]:text-on-surface/[0.38]',
    'group-data-[disabled=true]:group-data-[selected=false]:text-surface-container-highest/[0.38]',
    'group-data-[selected=true]:group-data-[pressed=true]:before:scale-[1.75]',
    'group-data-[disabled=true]:group-data-[selected=true]:before:bg-surface',
    'group-data-[disabled=true]:group-data-[selected=false]:before:bg-on-surface/[0.38]',
    'group-focus-within:after:bg-on-surface/[0.12]',
    'group-hover:after:bg-on-surface/[0.08]',
    'group-data-[pressed=true]:after:bg-on-surface/[0.12]',
    'group-data-[disabled=true]:after:hidden',
    'after:h-10 after:w-10 after:-z-1',
    'after:absolute',
    'after:rounded-full',
    'after:transition after:easing-emphasized after:duration-medium-1',
    'z-1',
  ],
  {
    variants: {
      color: {
        primary: [
          'group-data-[selected=true]:text-primary',
          'group-data-[selected=true]:before:bg-on-primary',
          'group-data-[selected=true]:group-focus-within:after:bg-primary/[0.12]',
          'group-data-[selected=true]:group-hover:after:bg-primary/[0.08]',
          'group-data-[selected=true]:group-data-[pressed=true]:after:bg-primary/[0.12]',
        ],
        secondary: [
          'group-data-[selected=true]:text-secondary',
          'group-data-[selected=true]:before:bg-on-secondary',
          'group-data-[selected=true]:group-focus-within:after:bg-secondary/[0.12]',
          'group-data-[selected=true]:group-hover:after:bg-secondary/[0.08]',
          'group-data-[selected=true]:group-data-[pressed=true]:after:bg-secondary/[0.12]',
        ],
        info: [
          'group-data-[selected=true]:text-info',
          'group-data-[selected=true]:before:bg-on-info',
          'group-data-[selected=true]:group-focus-within:after:bg-info/[0.12]',
          'group-data-[selected=true]:group-hover:after:bg-info/[0.08]',
          'group-data-[selected=true]:group-data-[pressed=true]:after:bg-info/[0.12]',
        ],
        success: [
          'group-data-[selected=true]:text-success',
          'group-data-[selected=true]:before:bg-on-success',
          'group-data-[selected=true]:group-focus-within:after:bg-success/[0.12]',
          'group-data-[selected=true]:group-hover:after:bg-success/[0.08]',
          'group-data-[selected=true]:group-data-[pressed=true]:after:bg-success/[0.12]',
        ],
        caution: [
          'group-data-[selected=true]:text-caution',
          'group-data-[selected=true]:before:bg-on-caution',
          'group-data-[selected=true]:group-focus-within:after:bg-caution/[0.12]',
          'group-data-[selected=true]:group-hover:after:bg-caution/[0.08]',
          'group-data-[selected=true]:group-data-[pressed=true]:after:bg-caution/[0.12]',
        ],
        critical: [
          'group-data-[selected=true]:text-critical',
          'group-data-[selected=true]:before:bg-on-critical',
          'group-data-[selected=true]:group-focus-within:after:bg-critical/[0.12]',
          'group-data-[selected=true]:group-hover:after:bg-critical/[0.08]',
          'group-data-[selected=true]:group-data-[pressed=true]:after:bg-critical/[0.12]',
        ],
      },
    },
    defaultVariants: {
      color: 'primary',
    },
  },
);
